import localFont from "next/font/local";
import "./globals.css";
import "./animations.css";
import Footer from "./footer";
import Header from "./header";

const hellix = localFont({
  src: [
    {
      path: "./fonts/Hellix-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Hellix-SemiBold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Hellix-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-hellix",
});

export const metadata = {
  title: "WiseNest Africa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${hellix.className} antialiased`}>
        <Header />
        {children}

        <Footer />
      </body>
    </html>
  );
}
